Introduce distributed Adaptive API
asyml/texar-pytorch pull request #326
Opened 2020-10-27 00:27 UTC by odp

This PR adds distributed Adaptive API to Texar-PyTorch with the help of [AdaptDL](https://adaptdl.readthedocs.io/en/latest/). 

Specifically 

1. `tx.distributed.AdaptiveDataParallel` which is similar to `torch.nn.parallel.DistributedDataParallel`, should be used to wrap the model, optimizer and lr_scheduler at the beginning of the code. This makes them distributed, restart-safe and adaptive.

2. `tx.distributed.AdaptiveDataIterator` which mimics `tx.data.DataIterator` but provides an adaptive, distributed version of it. Using this, the iterators become restart-safe (able to reposition correctly after a scale-up or scale-down of training) and distributed (data is automatically partitioned across replicas) 

Using these APIs and few others directly from the `adaptdl.torch` API, Texar-PyTorch models can be trained on an AdaptDL cluster in elastic, distributed data-parallel fashion. `examples/bert/bert_classifier_adaptive.py` is the adaptive version of `examples/bert/bert_classifier_main.py`  which demonstrates the use of above API. It can be trained on a cluster by running `examples/bert/run_bert_adaptive.sh` after setting up a AdaptDL kubernetes cluster or microk8s environment. 

The API is compatible with [standalone](https://adaptdl.readthedocs.io/en/latest/standalone-training.html) training on a single node machine or a multinode (non-k8s) cluster. However this mode does not support elasticity, but can be used for testing.

2020-10-29 16:18 UTC, hunterhector requested changes
Sorry for delaying the review. I have some general comments here.

I will still need to try run this myself to provide more comments, but we can fix some small stuff before that.

2020-11-03 00:24 UTC, odp commented on examples/bert/README.md
> +* Use of [Hyperopt]((https://github.com/hyperopt/hyperopt)) library to tune hyperparameters with
done

2020-11-03 00:24 UTC, odp commented on examples/bert/bert_classifier_adaptive.py
> +adaptdl.torch.init_process_group("nccl" if
done. Added links to AdaptDL documentation as well.

2020-11-03 00:35 UTC, odp commented on texar/torch/distributed/parallel.py
> +class AdaptiveDataParallel(adaptdl.torch.AdaptiveDataParallel):
High-level classes like the `BertClassifier` add their own members like `num_classes` or `is_binary` which are used inside the model training code. `AdaptiveDataParallel` strictly returns a `torch.nn.Module`. This results in a failure when these extra members are accessed from the model training code.

2020-11-03 00:35 UTC, odp commented on docker/Dockerfile
> +# Copyright 2019 The Texar Authors. All Rights Reserved.
sure

2020-11-03 03:04 UTC, odp commented on requirements.txt
> +adaptdl >= 0.2.4
Ok. Added a new group `dist`

2020-11-03 03:10 UTC, odp commented on examples/bert/requirements.txt
> +nni # used only in bert_executor_hypertuning_nni.py
Actually nni has some issues when used with the official pytorch 1.6.0 docker image. I have included the dependencies directly in the `Dockerfile`.

2020-11-11 20:40 UTC, hunterhector approved these changes

2020-11-12 03:23 UTC, merged